### ISSUE TITLE
About the responsiveness

### ISSUE THREAD

**Issue by chocoscoding** [shoaibkamalkhan/Banking-App#1]
Can you explain again the hamburger problem,

I would love to help you but I have to understand your problem before dipping my hand into your code

**Comment by shoaibkamalkhan** [comment]
Hi chocoscoding,

The idea behind what I am trying to do is have a dropdown hamburger menu for the 768px media query. Right now for mobile view I have the hamburger menu open as a full width menu that expands the length of the header. So, what is happening right now in the 768px breakpoint is that the menu drops down and I have used a 71px space for the top property. Is this the correct way of doing this? I have also used JS to animate the menu. Right now the in the 768px breakpoint, after you click the hamburger icon, the icon disappears. Can you please take a look at that too?

Thank you so much for taking a look at it!

**Comment by chocoscoding** [comment]
ok, i will pull your code and make some changes which i will explain
